# Generated by Django 3.2.6 on 2022-02-08 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ карты')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('male', models.CharField(blank=True, choices=[('1', 'мужской'), ('2', 'женский')], max_length=12, null=True, verbose_name='Пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Карта пациента',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='snapshot', verbose_name='Снимок')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='patient_chart.patientchart', verbose_name='Пациент')),
            ],
            options={
                'verbose_name_plural': 'Снимки',
            },
        ),
        migrations.CreateModel(
            name='CashWarrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashwarrants', to='patient_chart.patientchart', verbose_name='Пациент')),
            ],
            options={
                'verbose_name_plural': 'Кассовый ордер',
            },
        ),
    ]
